services:
  accounts:
    image: "ynacif31/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
        - ygorbank
  loans-api:
    image: "ynacif31/loans-api:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ygorbank
  cards-api:
    image: "ynacif31/cards-api:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ygorbank
networks:
    ygorbank:
        driver: "bridge"